import { Dataset } from "./types";

export const featuredPipeline = {
  title: "Revenue Delta Sync",
  summary:
    "Mission-critical pipeline reconciling order, payment, and inventory events every 5 minutes for executive reporting.",
  owner: "Data Platform",
  sla: "5m",
  lineage:
    "Kafka sales.events -> Bronze raw_sales_events -> Silver sales_cleansed -> Gold finance_revenue_daily",
};

export const medallionRows: { title: string; layer: Dataset["layer"]; items: Dataset[] }[] = [
  {
    title: "Recently Ingested (Bronze)",
    layer: "Bronze",
    items: [
      {
        id: "bronze-1",
        name: "raw_sales_events",
        description: "Unfiltered sales event stream from Kafka topics.",
        source: "Kafka: sales.events",
        lastUpdated: "2 min ago",
        health: "Healthy",
        rowCount: "132.4M",
        layer: "Bronze",
        tags: ["streaming", "cdc"],
      },
      {
        id: "bronze-2",
        name: "raw_inventory_snapshots",
        description: "Hourly S3 dumps from inventory service.",
        source: "S3: /landing/inventory/",
        lastUpdated: "11 min ago",
        health: "At Risk",
        rowCount: "18.7M",
        layer: "Bronze",
        tags: ["batch", "s3"],
      },
      {
        id: "bronze-3",
        name: "raw_customer_profiles",
        description: "Daily customer profile extracts before quality checks.",
        source: "S3: /landing/customers/",
        lastUpdated: "23 min ago",
        health: "Healthy",
        rowCount: "9.3M",
        layer: "Bronze",
        tags: ["pii", "daily"],
      },
    ],
  },
  {
    title: "Most Popular Tables (Silver)",
    layer: "Silver",
    items: [
      {
        id: "silver-1",
        name: "sales_cleansed",
        description: "Validated sales rows with standardized dimensions.",
        source: "Delta Lake: silver.sales_cleansed",
        lastUpdated: "4 min ago",
        health: "Healthy",
        rowCount: "78.1M",
        layer: "Silver",
        tags: ["quality", "analytics"],
      },
      {
        id: "silver-2",
        name: "customer_360",
        description: "Unified customer profile with deduplicated identities.",
        source: "Delta Lake: silver.customer_360",
        lastUpdated: "13 min ago",
        health: "Healthy",
        rowCount: "4.2M",
        layer: "Silver",
        tags: ["identity", "gold-candidate"],
      },
      {
        id: "silver-3",
        name: "inventory_clean",
        description: "Filtered inventory records with anomaly flags.",
        source: "Delta Lake: silver.inventory_clean",
        lastUpdated: "16 min ago",
        health: "At Risk",
        rowCount: "11.8M",
        layer: "Silver",
        tags: ["supply", "quality"],
      },
    ],
  },
  {
    title: "Business Ready (Gold)",
    layer: "Gold",
    items: [
      {
        id: "gold-1",
        name: "finance_revenue_daily",
        description: "Daily executive revenue metric table by market.",
        source: "Warehouse: gold.finance_revenue_daily",
        lastUpdated: "3 min ago",
        health: "Healthy",
        rowCount: "1.9M",
        layer: "Gold",
        tags: ["finance", "kpi"],
      },
      {
        id: "gold-2",
        name: "ops_fulfillment_scorecard",
        description: "SLA and fulfillment KPI aggregates for operations.",
        source: "Warehouse: gold.ops_fulfillment_scorecard",
        lastUpdated: "9 min ago",
        health: "Healthy",
        rowCount: "623K",
        layer: "Gold",
        tags: ["ops", "sla"],
      },
      {
        id: "gold-3",
        name: "sales_2023_snapshot",
        description: "Historical 2023 sales snapshot optimized for BI.",
        source: "Warehouse: gold.sales_2023_snapshot",
        lastUpdated: "1 hour ago",
        health: "At Risk",
        rowCount: "42.5M",
        layer: "Gold",
        tags: ["historical", "2023"],
      },
    ],
  },
];
