import { Dataset } from "./types";

export const featuredPipeline = {
  title: "BNPL Financial Integrity Pipeline",
  summary:
    "Mission-critical orchestration that reconciles invoices, settlements, repayments, and delinquency events into a trusted analytics core every 5 minutes.",
  owner: "Analytics Engineering",
  sla: "5m",
  lineage:
    "Kafka erp.transactions -> Bronze raw_erp_logs -> Silver bnpl_transaction_clean -> Gold fct_bnpl_repayment_daily",
};

export const medallionRows: { title: string; layer: Dataset["layer"]; items: Dataset[] }[] = [
  {
    title: "Recently Ingested (Bronze)",
    layer: "Bronze",
    items: [
      {
        id: "bronze-1",
        name: "raw_erp_logs",
        description: "Raw ERP transaction/change-log stream landing from Kafka.",
        source: "Kafka: erp.transactions",
        lastUpdated: "2 min ago",
        health: "Healthy",
        rowCount: "132.4M",
        layer: "Bronze",
        tags: ["streaming", "cdc"],
      },
      {
        id: "bronze-2",
        name: "raw_settlement_events",
        description: "Partner settlement payloads as landed files from ERP exports.",
        source: "S3: /landing/settlements/",
        lastUpdated: "11 min ago",
        health: "At Risk",
        rowCount: "18.7M",
        layer: "Bronze",
        tags: ["batch", "s3"],
      },
      {
        id: "bronze-3",
        name: "raw_repayment_status",
        description: "Repayment and delinquency status updates before validation.",
        source: "Kafka: bnpl.repayment_status",
        lastUpdated: "23 min ago",
        health: "Healthy",
        rowCount: "9.3M",
        layer: "Bronze",
        tags: ["pii", "daily"],
      },
    ],
  },
  {
    title: "Most Popular Tables (Silver)",
    layer: "Silver",
    items: [
      {
        id: "silver-1",
        name: "bnpl_transaction_clean",
        description: "Validated BNPL transactions with conformed merchant and customer keys.",
        source: "Delta Lake: silver.bnpl_transaction_clean",
        lastUpdated: "4 min ago",
        health: "Healthy",
        rowCount: "78.1M",
        layer: "Silver",
        tags: ["quality", "analytics"],
      },
      {
        id: "silver-2",
        name: "customer_credit_profile",
        description: "Unified customer credit profile with deduplicated identities.",
        source: "Delta Lake: silver.customer_credit_profile",
        lastUpdated: "13 min ago",
        health: "Healthy",
        rowCount: "4.2M",
        layer: "Silver",
        tags: ["identity", "gold-candidate"],
      },
      {
        id: "silver-3",
        name: "installment_schedule_clean",
        description: "Normalized installment schedule with anomaly flags and due-date quality checks.",
        source: "Delta Lake: silver.installment_schedule_clean",
        lastUpdated: "16 min ago",
        health: "At Risk",
        rowCount: "11.8M",
        layer: "Silver",
        tags: ["supply", "quality"],
      },
    ],
  },
  {
    title: "Business Ready (Gold)",
    layer: "Gold",
    items: [
      {
        id: "gold-1",
        name: "fct_bnpl_repayment_daily",
        description: "Daily fact table for repayment, principal outstanding, and fee revenue.",
        source: "Warehouse: gold.fct_bnpl_repayment_daily",
        lastUpdated: "3 min ago",
        health: "Healthy",
        rowCount: "1.9M",
        layer: "Gold",
        tags: ["finance", "kpi"],
      },
      {
        id: "gold-2",
        name: "fct_default_risk_monthly",
        description: "Default-risk and delinquency aggregates by customer and merchant cohorts.",
        source: "Warehouse: gold.fct_default_risk_monthly",
        lastUpdated: "9 min ago",
        health: "Healthy",
        rowCount: "623K",
        layer: "Gold",
        tags: ["ops", "sla"],
      },
      {
        id: "gold-3",
        name: "mart_bnpl_executive_kpis",
        description: "Executive-ready metrics mart powering BI and centralized metric definitions.",
        source: "Warehouse: gold.mart_bnpl_executive_kpis",
        lastUpdated: "1 hour ago",
        health: "At Risk",
        rowCount: "42.5M",
        layer: "Gold",
        tags: ["historical", "2023"],
      },
    ],
  },
];
